const assetsCDN = "https://cyan-2048.github.io/kaigram-assets/";

const HotCherry = [
	"AgADAQADwDZPEw",
	"AgADAgADwDZPEw",
	"AgADFQADwDZPEw",
	"AgADAwADwDZPEw",
	"AgADBQADwDZPEw",
	"AgADBgADwDZPEw",
	"AgADBwADwDZPEw",
	"AgADEwADwDZPEw",
	"AgADCAADwDZPEw",
	"AgADEQADwDZPEw",
	"AgADCQADwDZPEw",
	"AgADEAADwDZPEw",
	"AgADCgADwDZPEw",
	"AgADCwADwDZPEw",
	"AgADEgADwDZPEw",
	"AgADDAADwDZPEw",
	"AgADDQADwDZPEw",
	"AgADDgADwDZPEw",
	"AgADDwADwDZPEw",
	"AgADFAADwDZPEw",
	"AgADFgADwDZPEw",
	"AgADGAADwDZPEw",
	"AgADGQADwDZPEw",
	"AgADGgADwDZPEw",
	"AgADGwADwDZPEw",
	"AgADHAADwDZPEw",
	"AgADHQADwDZPEw",
	"AgADHgADwDZPEw",
	"AgADHwADwDZPEw",
	"AgADIAADwDZPEw",
	"AgADWgADwDZPEw",
	"AgAD6RsAAoV_EEk",
	"AgADnx4AAjpJKUk",
	"AgADexwAAujVUEk",
].map((a, i) => [a, assetsCDN + "stickers/HotCherry/" + ("000" + i).slice(-3) + ".png"]);

const UtyaDuck = [
	"AgAD8gADVp29Cg",
	"AgADBAEAAladvQo",
	"AgAD_gADVp29Cg",
	"AgAD_wADVp29Cg",
	"AgADAQEAAladvQo",
	"AgAD8wADVp29Cg",
	"AgAD9AADVp29Cg",
	"AgAD9QADVp29Cg",
	"AgAD9gADVp29Cg",
	"AgAD9wADVp29Cg",
	"AgAD-AADVp29Cg",
	"AgADBwEAAladvQo",
	"AgAD-QADVp29Cg",
	"AgADBQEAAladvQo",
	"AgAD-gADVp29Cg",
	"AgAD-wADVp29Cg",
	"AgADAgEAAladvQo",
	"AgADAwEAAladvQo",
	"AgADBgEAAladvQo",
	"AgADCAEAAladvQo",
	"AgADCQEAAladvQo",
	"AgADCwEAAladvQo",
	"AgADDAEAAladvQo",
	"AgADDQEAAladvQo",
	"AgADDgEAAladvQo",
	"AgAD2gEAAladvQo",
	"AgADSAIAAladvQo",
	"AgADSQIAAladvQo",
	"AgADTwIAAladvQo",
	"AgADSgIAAladvQo",
	"AgADryUAApuicEs",
	"AgADTgIAAladvQo",
	"AgADTQIAAladvQo",
	"AgADSwIAAladvQo",
	"AgADUAIAAladvQo",
	"AgADBQMAAladvQo",
	"AgADex0AAkWOKUg",
	"AgADQxgAArbIKUg",
	"AgADXhgAAogOKEg",
	"AgADRh4AAvyUOEk",
].map((a, i) => [a, assetsCDN + "stickers/UtyaDuck/" + ("000" + i).slice(-3) + ".png"]);

const MiBunny = [
	"AgADLQMAAsbMYwI",
	"AgADLgMAAsbMYwI",
	"AgADLwMAAsbMYwI",
	"AgADSAMAAsbMYwI",
	"AgADMgMAAsbMYwI",
	"AgADMwMAAsbMYwI",
	"AgADNAMAAsbMYwI",
	"AgADPAMAAsbMYwI",
	"AgADNQMAAsbMYwI",
	"AgADNgMAAsbMYwI",
	"AgADNwMAAsbMYwI",
	"AgADOAMAAsbMYwI",
	"AgADOgMAAsbMYwI",
	"AgADOwMAAsbMYwI",
	"AgADRwMAAsbMYwI",
	"AgADPQMAAsbMYwI",
	"AgADPgMAAsbMYwI",
	"AgADOQMAAsbMYwI",
	"AgADPwMAAsbMYwI",
	"AgADQAMAAsbMYwI",
	"AgADQQMAAsbMYwI",
	"AgADSQMAAsbMYwI",
	"AgADRAMAAsbMYwI",
	"AgADRQMAAsbMYwI",
	"AgADRgMAAsbMYwI",
	"AgADTAMAAsbMYwI",
	"AgADhwwAAnou0Eo",
	"AgAD8RIAAsYwAAFI",
].map((a, i) => [a, assetsCDN + "stickers/MiBunny/" + ("000" + i).slice(-3) + ".png"]);

const CorruptedEmojis = [
	"AgADKwwAAhU6cEg",
	"AgAD0wgAAmxpeEg",
	"AgADFwkAAobXeEg",
	"AgADtAkAAoK1eUg",
	"AgADTQkAAnYreUg",
	"AgADQAoAA4h4SA",
	"AgADgAoAAn-IeUg",
	"AgADPgoAAkRoeEg",
	"AgADGAwAAvE8eUg",
	"AgADcAkAAuE_eEg",
	"AgADGgcAAnT3eUg",
	"AgADowkAAmgQeUg",
	"AgAD2gcAAriHeEg",
	"AgAD1gkAAqn5eEg",
	"AgAD5wgAAjWteUg",
	"AgADNwgAArkCeEg",
	"AgADZQoAAh8veUg",
	"AgADlwoAAubLeEg",
	"AgADqQkAAkFKeUg",
	"AgADZgoAAgUzcUg",
	"AgADNggAAmb_cUg",
	"AgADdwkAAodNeEg",
	"AgADpgcAAqrieUg",
	"AgADiwgAAub8cUg",
	"AgADpQoAAn9_eUg",
	"AgADLQkAAun1eUg",
	"AgADWwgAApI_cEg",
	"AgADHAkAAjvxcUg",
	"AgADoQkAAkkNcUg",
	"AgADLQ4AAquAeEg",
	"AgADwgcAAnpyeEg",
	"AgADTAkAAoF-eUg",
	"AgADmwgAAuEyeEg",
	"AgADKQkAArZCeEg",
	"AgADPAkAAt2zeEg",
	"AgADyggAAu5ucEg",
	"AgADUQsAAuyPeEg",
	"AgAD8AkAAjD9eUg",
	"AgADSAkAAm6KeEg",
	"AgADBAkAAhKSeEg",
	"AgAD1woAAkaxeUg",
	"AgADQQkAApzGeUg",
	"AgADzggAAsG1cEg",
	"AgADTQcAAvwNeUg",
	"AgADOgkAAlIeeEg",
	"AgADswkAAnBRcEg",
	"AgADFAoAAjPpeEg",
	"AgADYAkAArJKcUg",
	"AgADNggAAg0ZeEg",
	"AgADQQoAAuSZyUg",
].map((a, i) => [a, assetsCDN + "stickers/NarkoLilAladin/" + ("000" + i).slice(-3) + ".png"]);

export const StickersMap = new Map<string, string>(
	HotCherry.concat(UtyaDuck).concat(MiBunny).concat(CorruptedEmojis) as any
);

console.error("StickersMap", StickersMap);
