/*
const assetsCDN = "https://cyan-2048.github.io/kaigram-assets/";

const HotCherry = [
	"AgADAQADwDZPEw",
	"AgADAgADwDZPEw",
	"AgADFQADwDZPEw",
	"AgADAwADwDZPEw",
	"AgADBQADwDZPEw",
	"AgADBgADwDZPEw",
	"AgADBwADwDZPEw",
	"AgADEwADwDZPEw",
	"AgADCAADwDZPEw",
	"AgADEQADwDZPEw",
	"AgADCQADwDZPEw",
	"AgADEAADwDZPEw",
	"AgADCgADwDZPEw",
	"AgADCwADwDZPEw",
	"AgADEgADwDZPEw",
	"AgADDAADwDZPEw",
	"AgADDQADwDZPEw",
	"AgADDgADwDZPEw",
	"AgADDwADwDZPEw",
	"AgADFAADwDZPEw",
	"AgADFgADwDZPEw",
	"AgADGAADwDZPEw",
	"AgADGQADwDZPEw",
	"AgADGgADwDZPEw",
	"AgADGwADwDZPEw",
	"AgADHAADwDZPEw",
	"AgADHQADwDZPEw",
	"AgADHgADwDZPEw",
	"AgADHwADwDZPEw",
	"AgADIAADwDZPEw",
	"AgADWgADwDZPEw",
	"AgAD6RsAAoV_EEk",
	"AgADnx4AAjpJKUk",
	"AgADexwAAujVUEk",
].map((a, i) => [a, assetsCDN + "stickers/HotCherry/" + ("000" + i).slice(-3) + ".png"]);

const UtyaDuck = [
	"AgAD8gADVp29Cg",
	"AgADBAEAAladvQo",
	"AgAD_gADVp29Cg",
	"AgAD_wADVp29Cg",
	"AgADAQEAAladvQo",
	"AgAD8wADVp29Cg",
	"AgAD9AADVp29Cg",
	"AgAD9QADVp29Cg",
	"AgAD9gADVp29Cg",
	"AgAD9wADVp29Cg",
	"AgAD-AADVp29Cg",
	"AgADBwEAAladvQo",
	"AgAD-QADVp29Cg",
	"AgADBQEAAladvQo",
	"AgAD-gADVp29Cg",
	"AgAD-wADVp29Cg",
	"AgADAgEAAladvQo",
	"AgADAwEAAladvQo",
	"AgADBgEAAladvQo",
	"AgADCAEAAladvQo",
	"AgADCQEAAladvQo",
	"AgADCwEAAladvQo",
	"AgADDAEAAladvQo",
	"AgADDQEAAladvQo",
	"AgADDgEAAladvQo",
	"AgAD2gEAAladvQo",
	"AgADSAIAAladvQo",
	"AgADSQIAAladvQo",
	"AgADTwIAAladvQo",
	"AgADSgIAAladvQo",
	"AgADryUAApuicEs",
	"AgADTgIAAladvQo",
	"AgADTQIAAladvQo",
	"AgADSwIAAladvQo",
	"AgADUAIAAladvQo",
	"AgADBQMAAladvQo",
	"AgADex0AAkWOKUg",
	"AgADQxgAArbIKUg",
	"AgADXhgAAogOKEg",
	"AgADRh4AAvyUOEk",
].map((a, i) => [a, assetsCDN + "stickers/UtyaDuck/" + ("000" + i).slice(-3) + ".png"]);

const MiBunny = [
	"AgADLQMAAsbMYwI",
	"AgADLgMAAsbMYwI",
	"AgADLwMAAsbMYwI",
	"AgADSAMAAsbMYwI",
	"AgADMgMAAsbMYwI",
	"AgADMwMAAsbMYwI",
	"AgADNAMAAsbMYwI",
	"AgADPAMAAsbMYwI",
	"AgADNQMAAsbMYwI",
	"AgADNgMAAsbMYwI",
	"AgADNwMAAsbMYwI",
	"AgADOAMAAsbMYwI",
	"AgADOgMAAsbMYwI",
	"AgADOwMAAsbMYwI",
	"AgADRwMAAsbMYwI",
	"AgADPQMAAsbMYwI",
	"AgADPgMAAsbMYwI",
	"AgADOQMAAsbMYwI",
	"AgADPwMAAsbMYwI",
	"AgADQAMAAsbMYwI",
	"AgADQQMAAsbMYwI",
	"AgADSQMAAsbMYwI",
	"AgADRAMAAsbMYwI",
	"AgADRQMAAsbMYwI",
	"AgADRgMAAsbMYwI",
	"AgADTAMAAsbMYwI",
	"AgADhwwAAnou0Eo",
	"AgAD8RIAAsYwAAFI",
].map((a, i) => [a, assetsCDN + "stickers/MiBunny/" + ("000" + i).slice(-3) + ".png"]);

const CorruptedEmojis = [
	"AgADKwwAAhU6cEg",
	"AgAD0wgAAmxpeEg",
	"AgADFwkAAobXeEg",
	"AgADtAkAAoK1eUg",
	"AgADTQkAAnYreUg",
	"AgADQAoAA4h4SA",
	"AgADgAoAAn-IeUg",
	"AgADPgoAAkRoeEg",
	"AgADGAwAAvE8eUg",
	"AgADcAkAAuE_eEg",
	"AgADGgcAAnT3eUg",
	"AgADowkAAmgQeUg",
	"AgAD2gcAAriHeEg",
	"AgAD1gkAAqn5eEg",
	"AgAD5wgAAjWteUg",
	"AgADNwgAArkCeEg",
	"AgADZQoAAh8veUg",
	"AgADlwoAAubLeEg",
	"AgADqQkAAkFKeUg",
	"AgADZgoAAgUzcUg",
	"AgADNggAAmb_cUg",
	"AgADdwkAAodNeEg",
	"AgADpgcAAqrieUg",
	"AgADiwgAAub8cUg",
	"AgADpQoAAn9_eUg",
	"AgADLQkAAun1eUg",
	"AgADWwgAApI_cEg",
	"AgADHAkAAjvxcUg",
	"AgADoQkAAkkNcUg",
	"AgADLQ4AAquAeEg",
	"AgADwgcAAnpyeEg",
	"AgADTAkAAoF-eUg",
	"AgADmwgAAuEyeEg",
	"AgADKQkAArZCeEg",
	"AgADPAkAAt2zeEg",
	"AgADyggAAu5ucEg",
	"AgADUQsAAuyPeEg",
	"AgAD8AkAAjD9eUg",
	"AgADSAkAAm6KeEg",
	"AgADBAkAAhKSeEg",
	"AgAD1woAAkaxeUg",
	"AgADQQkAApzGeUg",
	"AgADzggAAsG1cEg",
	"AgADTQcAAvwNeUg",
	"AgADOgkAAlIeeEg",
	"AgADswkAAnBRcEg",
	"AgADFAoAAjPpeEg",
	"AgADYAkAArJKcUg",
	"AgADNggAAg0ZeEg",
	"AgADQQoAAuSZyUg",
].map((a, i) => [a, assetsCDN + "stickers/NarkoLilAladin/" + ("000" + i).slice(-3) + ".png"]);
*/

export const StickersMap = new Map<string, string>([
	["AgADAQADwDZPEw", "https://cyan-2048.github.io/kaigram-assets/stickers/HotCherry/000.png"],
	["AgADAgADwDZPEw", "https://cyan-2048.github.io/kaigram-assets/stickers/HotCherry/001.png"],
	["AgADFQADwDZPEw", "https://cyan-2048.github.io/kaigram-assets/stickers/HotCherry/002.png"],
	["AgADAwADwDZPEw", "https://cyan-2048.github.io/kaigram-assets/stickers/HotCherry/003.png"],
	["AgADBQADwDZPEw", "https://cyan-2048.github.io/kaigram-assets/stickers/HotCherry/004.png"],
	["AgADBgADwDZPEw", "https://cyan-2048.github.io/kaigram-assets/stickers/HotCherry/005.png"],
	["AgADBwADwDZPEw", "https://cyan-2048.github.io/kaigram-assets/stickers/HotCherry/006.png"],
	["AgADEwADwDZPEw", "https://cyan-2048.github.io/kaigram-assets/stickers/HotCherry/007.png"],
	["AgADCAADwDZPEw", "https://cyan-2048.github.io/kaigram-assets/stickers/HotCherry/008.png"],
	["AgADEQADwDZPEw", "https://cyan-2048.github.io/kaigram-assets/stickers/HotCherry/009.png"],
	["AgADCQADwDZPEw", "https://cyan-2048.github.io/kaigram-assets/stickers/HotCherry/010.png"],
	["AgADEAADwDZPEw", "https://cyan-2048.github.io/kaigram-assets/stickers/HotCherry/011.png"],
	["AgADCgADwDZPEw", "https://cyan-2048.github.io/kaigram-assets/stickers/HotCherry/012.png"],
	["AgADCwADwDZPEw", "https://cyan-2048.github.io/kaigram-assets/stickers/HotCherry/013.png"],
	["AgADEgADwDZPEw", "https://cyan-2048.github.io/kaigram-assets/stickers/HotCherry/014.png"],
	["AgADDAADwDZPEw", "https://cyan-2048.github.io/kaigram-assets/stickers/HotCherry/015.png"],
	["AgADDQADwDZPEw", "https://cyan-2048.github.io/kaigram-assets/stickers/HotCherry/016.png"],
	["AgADDgADwDZPEw", "https://cyan-2048.github.io/kaigram-assets/stickers/HotCherry/017.png"],
	["AgADDwADwDZPEw", "https://cyan-2048.github.io/kaigram-assets/stickers/HotCherry/018.png"],
	["AgADFAADwDZPEw", "https://cyan-2048.github.io/kaigram-assets/stickers/HotCherry/019.png"],
	["AgADFgADwDZPEw", "https://cyan-2048.github.io/kaigram-assets/stickers/HotCherry/020.png"],
	["AgADGAADwDZPEw", "https://cyan-2048.github.io/kaigram-assets/stickers/HotCherry/021.png"],
	["AgADGQADwDZPEw", "https://cyan-2048.github.io/kaigram-assets/stickers/HotCherry/022.png"],
	["AgADGgADwDZPEw", "https://cyan-2048.github.io/kaigram-assets/stickers/HotCherry/023.png"],
	["AgADGwADwDZPEw", "https://cyan-2048.github.io/kaigram-assets/stickers/HotCherry/024.png"],
	["AgADHAADwDZPEw", "https://cyan-2048.github.io/kaigram-assets/stickers/HotCherry/025.png"],
	["AgADHQADwDZPEw", "https://cyan-2048.github.io/kaigram-assets/stickers/HotCherry/026.png"],
	["AgADHgADwDZPEw", "https://cyan-2048.github.io/kaigram-assets/stickers/HotCherry/027.png"],
	["AgADHwADwDZPEw", "https://cyan-2048.github.io/kaigram-assets/stickers/HotCherry/028.png"],
	["AgADIAADwDZPEw", "https://cyan-2048.github.io/kaigram-assets/stickers/HotCherry/029.png"],
	["AgADWgADwDZPEw", "https://cyan-2048.github.io/kaigram-assets/stickers/HotCherry/030.png"],
	["AgAD6RsAAoV_EEk", "https://cyan-2048.github.io/kaigram-assets/stickers/HotCherry/031.png"],
	["AgADnx4AAjpJKUk", "https://cyan-2048.github.io/kaigram-assets/stickers/HotCherry/032.png"],
	["AgADexwAAujVUEk", "https://cyan-2048.github.io/kaigram-assets/stickers/HotCherry/033.png"],
	["AgAD8gADVp29Cg", "https://cyan-2048.github.io/kaigram-assets/stickers/UtyaDuck/000.png"],
	["AgADBAEAAladvQo", "https://cyan-2048.github.io/kaigram-assets/stickers/UtyaDuck/001.png"],
	["AgAD_gADVp29Cg", "https://cyan-2048.github.io/kaigram-assets/stickers/UtyaDuck/002.png"],
	["AgAD_wADVp29Cg", "https://cyan-2048.github.io/kaigram-assets/stickers/UtyaDuck/003.png"],
	["AgADAQEAAladvQo", "https://cyan-2048.github.io/kaigram-assets/stickers/UtyaDuck/004.png"],
	["AgAD8wADVp29Cg", "https://cyan-2048.github.io/kaigram-assets/stickers/UtyaDuck/005.png"],
	["AgAD9AADVp29Cg", "https://cyan-2048.github.io/kaigram-assets/stickers/UtyaDuck/006.png"],
	["AgAD9QADVp29Cg", "https://cyan-2048.github.io/kaigram-assets/stickers/UtyaDuck/007.png"],
	["AgAD9gADVp29Cg", "https://cyan-2048.github.io/kaigram-assets/stickers/UtyaDuck/008.png"],
	["AgAD9wADVp29Cg", "https://cyan-2048.github.io/kaigram-assets/stickers/UtyaDuck/009.png"],
	["AgAD-AADVp29Cg", "https://cyan-2048.github.io/kaigram-assets/stickers/UtyaDuck/010.png"],
	["AgADBwEAAladvQo", "https://cyan-2048.github.io/kaigram-assets/stickers/UtyaDuck/011.png"],
	["AgAD-QADVp29Cg", "https://cyan-2048.github.io/kaigram-assets/stickers/UtyaDuck/012.png"],
	["AgADBQEAAladvQo", "https://cyan-2048.github.io/kaigram-assets/stickers/UtyaDuck/013.png"],
	["AgAD-gADVp29Cg", "https://cyan-2048.github.io/kaigram-assets/stickers/UtyaDuck/014.png"],
	["AgAD-wADVp29Cg", "https://cyan-2048.github.io/kaigram-assets/stickers/UtyaDuck/015.png"],
	["AgADAgEAAladvQo", "https://cyan-2048.github.io/kaigram-assets/stickers/UtyaDuck/016.png"],
	["AgADAwEAAladvQo", "https://cyan-2048.github.io/kaigram-assets/stickers/UtyaDuck/017.png"],
	["AgADBgEAAladvQo", "https://cyan-2048.github.io/kaigram-assets/stickers/UtyaDuck/018.png"],
	["AgADCAEAAladvQo", "https://cyan-2048.github.io/kaigram-assets/stickers/UtyaDuck/019.png"],
	["AgADCQEAAladvQo", "https://cyan-2048.github.io/kaigram-assets/stickers/UtyaDuck/020.png"],
	["AgADCwEAAladvQo", "https://cyan-2048.github.io/kaigram-assets/stickers/UtyaDuck/021.png"],
	["AgADDAEAAladvQo", "https://cyan-2048.github.io/kaigram-assets/stickers/UtyaDuck/022.png"],
	["AgADDQEAAladvQo", "https://cyan-2048.github.io/kaigram-assets/stickers/UtyaDuck/023.png"],
	["AgADDgEAAladvQo", "https://cyan-2048.github.io/kaigram-assets/stickers/UtyaDuck/024.png"],
	["AgAD2gEAAladvQo", "https://cyan-2048.github.io/kaigram-assets/stickers/UtyaDuck/025.png"],
	["AgADSAIAAladvQo", "https://cyan-2048.github.io/kaigram-assets/stickers/UtyaDuck/026.png"],
	["AgADSQIAAladvQo", "https://cyan-2048.github.io/kaigram-assets/stickers/UtyaDuck/027.png"],
	["AgADTwIAAladvQo", "https://cyan-2048.github.io/kaigram-assets/stickers/UtyaDuck/028.png"],
	["AgADSgIAAladvQo", "https://cyan-2048.github.io/kaigram-assets/stickers/UtyaDuck/029.png"],
	["AgADryUAApuicEs", "https://cyan-2048.github.io/kaigram-assets/stickers/UtyaDuck/030.png"],
	["AgADTgIAAladvQo", "https://cyan-2048.github.io/kaigram-assets/stickers/UtyaDuck/031.png"],
	["AgADTQIAAladvQo", "https://cyan-2048.github.io/kaigram-assets/stickers/UtyaDuck/032.png"],
	["AgADSwIAAladvQo", "https://cyan-2048.github.io/kaigram-assets/stickers/UtyaDuck/033.png"],
	["AgADUAIAAladvQo", "https://cyan-2048.github.io/kaigram-assets/stickers/UtyaDuck/034.png"],
	["AgADBQMAAladvQo", "https://cyan-2048.github.io/kaigram-assets/stickers/UtyaDuck/035.png"],
	["AgADex0AAkWOKUg", "https://cyan-2048.github.io/kaigram-assets/stickers/UtyaDuck/036.png"],
	["AgADQxgAArbIKUg", "https://cyan-2048.github.io/kaigram-assets/stickers/UtyaDuck/037.png"],
	["AgADXhgAAogOKEg", "https://cyan-2048.github.io/kaigram-assets/stickers/UtyaDuck/038.png"],
	["AgADRh4AAvyUOEk", "https://cyan-2048.github.io/kaigram-assets/stickers/UtyaDuck/039.png"],
	["AgADLQMAAsbMYwI", "https://cyan-2048.github.io/kaigram-assets/stickers/MiBunny/000.png"],
	["AgADLgMAAsbMYwI", "https://cyan-2048.github.io/kaigram-assets/stickers/MiBunny/001.png"],
	["AgADLwMAAsbMYwI", "https://cyan-2048.github.io/kaigram-assets/stickers/MiBunny/002.png"],
	["AgADSAMAAsbMYwI", "https://cyan-2048.github.io/kaigram-assets/stickers/MiBunny/003.png"],
	["AgADMgMAAsbMYwI", "https://cyan-2048.github.io/kaigram-assets/stickers/MiBunny/004.png"],
	["AgADMwMAAsbMYwI", "https://cyan-2048.github.io/kaigram-assets/stickers/MiBunny/005.png"],
	["AgADNAMAAsbMYwI", "https://cyan-2048.github.io/kaigram-assets/stickers/MiBunny/006.png"],
	["AgADPAMAAsbMYwI", "https://cyan-2048.github.io/kaigram-assets/stickers/MiBunny/007.png"],
	["AgADNQMAAsbMYwI", "https://cyan-2048.github.io/kaigram-assets/stickers/MiBunny/008.png"],
	["AgADNgMAAsbMYwI", "https://cyan-2048.github.io/kaigram-assets/stickers/MiBunny/009.png"],
	["AgADNwMAAsbMYwI", "https://cyan-2048.github.io/kaigram-assets/stickers/MiBunny/010.png"],
	["AgADOAMAAsbMYwI", "https://cyan-2048.github.io/kaigram-assets/stickers/MiBunny/011.png"],
	["AgADOgMAAsbMYwI", "https://cyan-2048.github.io/kaigram-assets/stickers/MiBunny/012.png"],
	["AgADOwMAAsbMYwI", "https://cyan-2048.github.io/kaigram-assets/stickers/MiBunny/013.png"],
	["AgADRwMAAsbMYwI", "https://cyan-2048.github.io/kaigram-assets/stickers/MiBunny/014.png"],
	["AgADPQMAAsbMYwI", "https://cyan-2048.github.io/kaigram-assets/stickers/MiBunny/015.png"],
	["AgADPgMAAsbMYwI", "https://cyan-2048.github.io/kaigram-assets/stickers/MiBunny/016.png"],
	["AgADOQMAAsbMYwI", "https://cyan-2048.github.io/kaigram-assets/stickers/MiBunny/017.png"],
	["AgADPwMAAsbMYwI", "https://cyan-2048.github.io/kaigram-assets/stickers/MiBunny/018.png"],
	["AgADQAMAAsbMYwI", "https://cyan-2048.github.io/kaigram-assets/stickers/MiBunny/019.png"],
	["AgADQQMAAsbMYwI", "https://cyan-2048.github.io/kaigram-assets/stickers/MiBunny/020.png"],
	["AgADSQMAAsbMYwI", "https://cyan-2048.github.io/kaigram-assets/stickers/MiBunny/021.png"],
	["AgADRAMAAsbMYwI", "https://cyan-2048.github.io/kaigram-assets/stickers/MiBunny/022.png"],
	["AgADRQMAAsbMYwI", "https://cyan-2048.github.io/kaigram-assets/stickers/MiBunny/023.png"],
	["AgADRgMAAsbMYwI", "https://cyan-2048.github.io/kaigram-assets/stickers/MiBunny/024.png"],
	["AgADTAMAAsbMYwI", "https://cyan-2048.github.io/kaigram-assets/stickers/MiBunny/025.png"],
	["AgADhwwAAnou0Eo", "https://cyan-2048.github.io/kaigram-assets/stickers/MiBunny/026.png"],
	["AgAD8RIAAsYwAAFI", "https://cyan-2048.github.io/kaigram-assets/stickers/MiBunny/027.png"],
	["AgADKwwAAhU6cEg", "https://cyan-2048.github.io/kaigram-assets/stickers/NarkoLilAladin/000.png"],
	["AgAD0wgAAmxpeEg", "https://cyan-2048.github.io/kaigram-assets/stickers/NarkoLilAladin/001.png"],
	["AgADFwkAAobXeEg", "https://cyan-2048.github.io/kaigram-assets/stickers/NarkoLilAladin/002.png"],
	["AgADtAkAAoK1eUg", "https://cyan-2048.github.io/kaigram-assets/stickers/NarkoLilAladin/003.png"],
	["AgADTQkAAnYreUg", "https://cyan-2048.github.io/kaigram-assets/stickers/NarkoLilAladin/004.png"],
	["AgADQAoAA4h4SA", "https://cyan-2048.github.io/kaigram-assets/stickers/NarkoLilAladin/005.png"],
	["AgADgAoAAn-IeUg", "https://cyan-2048.github.io/kaigram-assets/stickers/NarkoLilAladin/006.png"],
	["AgADPgoAAkRoeEg", "https://cyan-2048.github.io/kaigram-assets/stickers/NarkoLilAladin/007.png"],
	["AgADGAwAAvE8eUg", "https://cyan-2048.github.io/kaigram-assets/stickers/NarkoLilAladin/008.png"],
	["AgADcAkAAuE_eEg", "https://cyan-2048.github.io/kaigram-assets/stickers/NarkoLilAladin/009.png"],
	["AgADGgcAAnT3eUg", "https://cyan-2048.github.io/kaigram-assets/stickers/NarkoLilAladin/010.png"],
	["AgADowkAAmgQeUg", "https://cyan-2048.github.io/kaigram-assets/stickers/NarkoLilAladin/011.png"],
	["AgAD2gcAAriHeEg", "https://cyan-2048.github.io/kaigram-assets/stickers/NarkoLilAladin/012.png"],
	["AgAD1gkAAqn5eEg", "https://cyan-2048.github.io/kaigram-assets/stickers/NarkoLilAladin/013.png"],
	["AgAD5wgAAjWteUg", "https://cyan-2048.github.io/kaigram-assets/stickers/NarkoLilAladin/014.png"],
	["AgADNwgAArkCeEg", "https://cyan-2048.github.io/kaigram-assets/stickers/NarkoLilAladin/015.png"],
	["AgADZQoAAh8veUg", "https://cyan-2048.github.io/kaigram-assets/stickers/NarkoLilAladin/016.png"],
	["AgADlwoAAubLeEg", "https://cyan-2048.github.io/kaigram-assets/stickers/NarkoLilAladin/017.png"],
	["AgADqQkAAkFKeUg", "https://cyan-2048.github.io/kaigram-assets/stickers/NarkoLilAladin/018.png"],
	["AgADZgoAAgUzcUg", "https://cyan-2048.github.io/kaigram-assets/stickers/NarkoLilAladin/019.png"],
	["AgADNggAAmb_cUg", "https://cyan-2048.github.io/kaigram-assets/stickers/NarkoLilAladin/020.png"],
	["AgADdwkAAodNeEg", "https://cyan-2048.github.io/kaigram-assets/stickers/NarkoLilAladin/021.png"],
	["AgADpgcAAqrieUg", "https://cyan-2048.github.io/kaigram-assets/stickers/NarkoLilAladin/022.png"],
	["AgADiwgAAub8cUg", "https://cyan-2048.github.io/kaigram-assets/stickers/NarkoLilAladin/023.png"],
	["AgADpQoAAn9_eUg", "https://cyan-2048.github.io/kaigram-assets/stickers/NarkoLilAladin/024.png"],
	["AgADLQkAAun1eUg", "https://cyan-2048.github.io/kaigram-assets/stickers/NarkoLilAladin/025.png"],
	["AgADWwgAApI_cEg", "https://cyan-2048.github.io/kaigram-assets/stickers/NarkoLilAladin/026.png"],
	["AgADHAkAAjvxcUg", "https://cyan-2048.github.io/kaigram-assets/stickers/NarkoLilAladin/027.png"],
	["AgADoQkAAkkNcUg", "https://cyan-2048.github.io/kaigram-assets/stickers/NarkoLilAladin/028.png"],
	["AgADLQ4AAquAeEg", "https://cyan-2048.github.io/kaigram-assets/stickers/NarkoLilAladin/029.png"],
	["AgADwgcAAnpyeEg", "https://cyan-2048.github.io/kaigram-assets/stickers/NarkoLilAladin/030.png"],
	["AgADTAkAAoF-eUg", "https://cyan-2048.github.io/kaigram-assets/stickers/NarkoLilAladin/031.png"],
	["AgADmwgAAuEyeEg", "https://cyan-2048.github.io/kaigram-assets/stickers/NarkoLilAladin/032.png"],
	["AgADKQkAArZCeEg", "https://cyan-2048.github.io/kaigram-assets/stickers/NarkoLilAladin/033.png"],
	["AgADPAkAAt2zeEg", "https://cyan-2048.github.io/kaigram-assets/stickers/NarkoLilAladin/034.png"],
	["AgADyggAAu5ucEg", "https://cyan-2048.github.io/kaigram-assets/stickers/NarkoLilAladin/035.png"],
	["AgADUQsAAuyPeEg", "https://cyan-2048.github.io/kaigram-assets/stickers/NarkoLilAladin/036.png"],
	["AgAD8AkAAjD9eUg", "https://cyan-2048.github.io/kaigram-assets/stickers/NarkoLilAladin/037.png"],
	["AgADSAkAAm6KeEg", "https://cyan-2048.github.io/kaigram-assets/stickers/NarkoLilAladin/038.png"],
	["AgADBAkAAhKSeEg", "https://cyan-2048.github.io/kaigram-assets/stickers/NarkoLilAladin/039.png"],
	["AgAD1woAAkaxeUg", "https://cyan-2048.github.io/kaigram-assets/stickers/NarkoLilAladin/040.png"],
	["AgADQQkAApzGeUg", "https://cyan-2048.github.io/kaigram-assets/stickers/NarkoLilAladin/041.png"],
	["AgADzggAAsG1cEg", "https://cyan-2048.github.io/kaigram-assets/stickers/NarkoLilAladin/042.png"],
	["AgADTQcAAvwNeUg", "https://cyan-2048.github.io/kaigram-assets/stickers/NarkoLilAladin/043.png"],
	["AgADOgkAAlIeeEg", "https://cyan-2048.github.io/kaigram-assets/stickers/NarkoLilAladin/044.png"],
	["AgADswkAAnBRcEg", "https://cyan-2048.github.io/kaigram-assets/stickers/NarkoLilAladin/045.png"],
	["AgADFAoAAjPpeEg", "https://cyan-2048.github.io/kaigram-assets/stickers/NarkoLilAladin/046.png"],
	["AgADYAkAArJKcUg", "https://cyan-2048.github.io/kaigram-assets/stickers/NarkoLilAladin/047.png"],
	["AgADNggAAg0ZeEg", "https://cyan-2048.github.io/kaigram-assets/stickers/NarkoLilAladin/048.png"],
	["AgADQQoAAuSZyUg", "https://cyan-2048.github.io/kaigram-assets/stickers/NarkoLilAladin/049.png"],
]);
