/*
const assetsCDN = "https://cyan-2048.github.io/kaigram-assets/";

const HotCherry = [
	"AgADAQADwDZPEw",
	"AgADAgADwDZPEw",
	"AgADFQADwDZPEw",
	"AgADAwADwDZPEw",
	"AgADBQADwDZPEw",
	"AgADBgADwDZPEw",
	"AgADBwADwDZPEw",
	"AgADEwADwDZPEw",
	"AgADCAADwDZPEw",
	"AgADEQADwDZPEw",
	"AgADCQADwDZPEw",
	"AgADEAADwDZPEw",
	"AgADCgADwDZPEw",
	"AgADCwADwDZPEw",
	"AgADEgADwDZPEw",
	"AgADDAADwDZPEw",
	"AgADDQADwDZPEw",
	"AgADDgADwDZPEw",
	"AgADDwADwDZPEw",
	"AgADFAADwDZPEw",
	"AgADFgADwDZPEw",
	"AgADGAADwDZPEw",
	"AgADGQADwDZPEw",
	"AgADGgADwDZPEw",
	"AgADGwADwDZPEw",
	"AgADHAADwDZPEw",
	"AgADHQADwDZPEw",
	"AgADHgADwDZPEw",
	"AgADHwADwDZPEw",
	"AgADIAADwDZPEw",
	"AgADWgADwDZPEw",
	"AgAD6RsAAoV_EEk",
	"AgADnx4AAjpJKUk",
	"AgADexwAAujVUEk",
].map((a, i) => [a, assetsCDN + "stickers/HotCherry/" + ("000" + i).slice(-3) + ".png"]);

const UtyaDuck = [
	"AgAD8gADVp29Cg",
	"AgADBAEAAladvQo",
	"AgAD_gADVp29Cg",
	"AgAD_wADVp29Cg",
	"AgADAQEAAladvQo",
	"AgAD8wADVp29Cg",
	"AgAD9AADVp29Cg",
	"AgAD9QADVp29Cg",
	"AgAD9gADVp29Cg",
	"AgAD9wADVp29Cg",
	"AgAD-AADVp29Cg",
	"AgADBwEAAladvQo",
	"AgAD-QADVp29Cg",
	"AgADBQEAAladvQo",
	"AgAD-gADVp29Cg",
	"AgAD-wADVp29Cg",
	"AgADAgEAAladvQo",
	"AgADAwEAAladvQo",
	"AgADBgEAAladvQo",
	"AgADCAEAAladvQo",
	"AgADCQEAAladvQo",
	"AgADCwEAAladvQo",
	"AgADDAEAAladvQo",
	"AgADDQEAAladvQo",
	"AgADDgEAAladvQo",
	"AgAD2gEAAladvQo",
	"AgADSAIAAladvQo",
	"AgADSQIAAladvQo",
	"AgADTwIAAladvQo",
	"AgADSgIAAladvQo",
	"AgADryUAApuicEs",
	"AgADTgIAAladvQo",
	"AgADTQIAAladvQo",
	"AgADSwIAAladvQo",
	"AgADUAIAAladvQo",
	"AgADBQMAAladvQo",
	"AgADex0AAkWOKUg",
	"AgADQxgAArbIKUg",
	"AgADXhgAAogOKEg",
	"AgADRh4AAvyUOEk",
].map((a, i) => [a, assetsCDN + "stickers/UtyaDuck/" + ("000" + i).slice(-3) + ".png"]);

const MiBunny = [
	"AgADLQMAAsbMYwI",
	"AgADLgMAAsbMYwI",
	"AgADLwMAAsbMYwI",
	"AgADSAMAAsbMYwI",
	"AgADMgMAAsbMYwI",
	"AgADMwMAAsbMYwI",
	"AgADNAMAAsbMYwI",
	"AgADPAMAAsbMYwI",
	"AgADNQMAAsbMYwI",
	"AgADNgMAAsbMYwI",
	"AgADNwMAAsbMYwI",
	"AgADOAMAAsbMYwI",
	"AgADOgMAAsbMYwI",
	"AgADOwMAAsbMYwI",
	"AgADRwMAAsbMYwI",
	"AgADPQMAAsbMYwI",
	"AgADPgMAAsbMYwI",
	"AgADOQMAAsbMYwI",
	"AgADPwMAAsbMYwI",
	"AgADQAMAAsbMYwI",
	"AgADQQMAAsbMYwI",
	"AgADSQMAAsbMYwI",
	"AgADRAMAAsbMYwI",
	"AgADRQMAAsbMYwI",
	"AgADRgMAAsbMYwI",
	"AgADTAMAAsbMYwI",
	"AgADhwwAAnou0Eo",
	"AgAD8RIAAsYwAAFI",
].map((a, i) => [a, assetsCDN + "stickers/MiBunny/" + ("000" + i).slice(-3) + ".png"]);

const CorruptedEmojis = [
	"AgADKwwAAhU6cEg",
	"AgAD0wgAAmxpeEg",
	"AgADFwkAAobXeEg",
	"AgADtAkAAoK1eUg",
	"AgADTQkAAnYreUg",
	"AgADQAoAA4h4SA",
	"AgADgAoAAn-IeUg",
	"AgADPgoAAkRoeEg",
	"AgADGAwAAvE8eUg",
	"AgADcAkAAuE_eEg",
	"AgADGgcAAnT3eUg",
	"AgADowkAAmgQeUg",
	"AgAD2gcAAriHeEg",
	"AgAD1gkAAqn5eEg",
	"AgAD5wgAAjWteUg",
	"AgADNwgAArkCeEg",
	"AgADZQoAAh8veUg",
	"AgADlwoAAubLeEg",
	"AgADqQkAAkFKeUg",
	"AgADZgoAAgUzcUg",
	"AgADNggAAmb_cUg",
	"AgADdwkAAodNeEg",
	"AgADpgcAAqrieUg",
	"AgADiwgAAub8cUg",
	"AgADpQoAAn9_eUg",
	"AgADLQkAAun1eUg",
	"AgADWwgAApI_cEg",
	"AgADHAkAAjvxcUg",
	"AgADoQkAAkkNcUg",
	"AgADLQ4AAquAeEg",
	"AgADwgcAAnpyeEg",
	"AgADTAkAAoF-eUg",
	"AgADmwgAAuEyeEg",
	"AgADKQkAArZCeEg",
	"AgADPAkAAt2zeEg",
	"AgADyggAAu5ucEg",
	"AgADUQsAAuyPeEg",
	"AgAD8AkAAjD9eUg",
	"AgADSAkAAm6KeEg",
	"AgADBAkAAhKSeEg",
	"AgAD1woAAkaxeUg",
	"AgADQQkAApzGeUg",
	"AgADzggAAsG1cEg",
	"AgADTQcAAvwNeUg",
	"AgADOgkAAlIeeEg",
	"AgADswkAAnBRcEg",
	"AgADFAoAAjPpeEg",
	"AgADYAkAArJKcUg",
	"AgADNggAAg0ZeEg",
	"AgADQQoAAuSZyUg",
].map((a, i) => [a, assetsCDN + "stickers/NarkoLilAladin/" + ("000" + i).slice(-3) + ".png"]);
*/

export default {
	AgADAQADwDZPEw: "HotCherry/000.png",
	AgADAgADwDZPEw: "HotCherry/001.png",
	AgADFQADwDZPEw: "HotCherry/002.png",
	AgADAwADwDZPEw: "HotCherry/003.png",
	AgADBQADwDZPEw: "HotCherry/004.png",
	AgADBgADwDZPEw: "HotCherry/005.png",
	AgADBwADwDZPEw: "HotCherry/006.png",
	AgADEwADwDZPEw: "HotCherry/007.png",
	AgADCAADwDZPEw: "HotCherry/008.png",
	AgADEQADwDZPEw: "HotCherry/009.png",
	AgADCQADwDZPEw: "HotCherry/010.png",
	AgADEAADwDZPEw: "HotCherry/011.png",
	AgADCgADwDZPEw: "HotCherry/012.png",
	AgADCwADwDZPEw: "HotCherry/013.png",
	AgADEgADwDZPEw: "HotCherry/014.png",
	AgADDAADwDZPEw: "HotCherry/015.png",
	AgADDQADwDZPEw: "HotCherry/016.png",
	AgADDgADwDZPEw: "HotCherry/017.png",
	AgADDwADwDZPEw: "HotCherry/018.png",
	AgADFAADwDZPEw: "HotCherry/019.png",
	AgADFgADwDZPEw: "HotCherry/020.png",
	AgADGAADwDZPEw: "HotCherry/021.png",
	AgADGQADwDZPEw: "HotCherry/022.png",
	AgADGgADwDZPEw: "HotCherry/023.png",
	AgADGwADwDZPEw: "HotCherry/024.png",
	AgADHAADwDZPEw: "HotCherry/025.png",
	AgADHQADwDZPEw: "HotCherry/026.png",
	AgADHgADwDZPEw: "HotCherry/027.png",
	AgADHwADwDZPEw: "HotCherry/028.png",
	AgADIAADwDZPEw: "HotCherry/029.png",
	AgADWgADwDZPEw: "HotCherry/030.png",
	AgAD6RsAAoV_EEk: "HotCherry/031.png",
	AgADnx4AAjpJKUk: "HotCherry/032.png",
	AgADexwAAujVUEk: "HotCherry/033.png",
	AgAD8gADVp29Cg: "UtyaDuck/000.png",
	AgADBAEAAladvQo: "UtyaDuck/001.png",
	AgAD_gADVp29Cg: "UtyaDuck/002.png",
	AgAD_wADVp29Cg: "UtyaDuck/003.png",
	AgADAQEAAladvQo: "UtyaDuck/004.png",
	AgAD8wADVp29Cg: "UtyaDuck/005.png",
	AgAD9AADVp29Cg: "UtyaDuck/006.png",
	AgAD9QADVp29Cg: "UtyaDuck/007.png",
	AgAD9gADVp29Cg: "UtyaDuck/008.png",
	AgAD9wADVp29Cg: "UtyaDuck/009.png",
	"AgAD-AADVp29Cg": "UtyaDuck/010.png",
	AgADBwEAAladvQo: "UtyaDuck/011.png",
	"AgAD-QADVp29Cg": "UtyaDuck/012.png",
	AgADBQEAAladvQo: "UtyaDuck/013.png",
	"AgAD-gADVp29Cg": "UtyaDuck/014.png",
	"AgAD-wADVp29Cg": "UtyaDuck/015.png",
	AgADAgEAAladvQo: "UtyaDuck/016.png",
	AgADAwEAAladvQo: "UtyaDuck/017.png",
	AgADBgEAAladvQo: "UtyaDuck/018.png",
	AgADCAEAAladvQo: "UtyaDuck/019.png",
	AgADCQEAAladvQo: "UtyaDuck/020.png",
	AgADCwEAAladvQo: "UtyaDuck/021.png",
	AgADDAEAAladvQo: "UtyaDuck/022.png",
	AgADDQEAAladvQo: "UtyaDuck/023.png",
	AgADDgEAAladvQo: "UtyaDuck/024.png",
	AgAD2gEAAladvQo: "UtyaDuck/025.png",
	AgADSAIAAladvQo: "UtyaDuck/026.png",
	AgADSQIAAladvQo: "UtyaDuck/027.png",
	AgADTwIAAladvQo: "UtyaDuck/028.png",
	AgADSgIAAladvQo: "UtyaDuck/029.png",
	AgADryUAApuicEs: "UtyaDuck/030.png",
	AgADTgIAAladvQo: "UtyaDuck/031.png",
	AgADTQIAAladvQo: "UtyaDuck/032.png",
	AgADSwIAAladvQo: "UtyaDuck/033.png",
	AgADUAIAAladvQo: "UtyaDuck/034.png",
	AgADBQMAAladvQo: "UtyaDuck/035.png",
	AgADex0AAkWOKUg: "UtyaDuck/036.png",
	AgADQxgAArbIKUg: "UtyaDuck/037.png",
	AgADXhgAAogOKEg: "UtyaDuck/038.png",
	AgADRh4AAvyUOEk: "UtyaDuck/039.png",
	AgADLQMAAsbMYwI: "MiBunny/000.png",
	AgADLgMAAsbMYwI: "MiBunny/001.png",
	AgADLwMAAsbMYwI: "MiBunny/002.png",
	AgADSAMAAsbMYwI: "MiBunny/003.png",
	AgADMgMAAsbMYwI: "MiBunny/004.png",
	AgADMwMAAsbMYwI: "MiBunny/005.png",
	AgADNAMAAsbMYwI: "MiBunny/006.png",
	AgADPAMAAsbMYwI: "MiBunny/007.png",
	AgADNQMAAsbMYwI: "MiBunny/008.png",
	AgADNgMAAsbMYwI: "MiBunny/009.png",
	AgADNwMAAsbMYwI: "MiBunny/010.png",
	AgADOAMAAsbMYwI: "MiBunny/011.png",
	AgADOgMAAsbMYwI: "MiBunny/012.png",
	AgADOwMAAsbMYwI: "MiBunny/013.png",
	AgADRwMAAsbMYwI: "MiBunny/014.png",
	AgADPQMAAsbMYwI: "MiBunny/015.png",
	AgADPgMAAsbMYwI: "MiBunny/016.png",
	AgADOQMAAsbMYwI: "MiBunny/017.png",
	AgADPwMAAsbMYwI: "MiBunny/018.png",
	AgADQAMAAsbMYwI: "MiBunny/019.png",
	AgADQQMAAsbMYwI: "MiBunny/020.png",
	AgADSQMAAsbMYwI: "MiBunny/021.png",
	AgADRAMAAsbMYwI: "MiBunny/022.png",
	AgADRQMAAsbMYwI: "MiBunny/023.png",
	AgADRgMAAsbMYwI: "MiBunny/024.png",
	AgADTAMAAsbMYwI: "MiBunny/025.png",
	AgADhwwAAnou0Eo: "MiBunny/026.png",
	AgAD8RIAAsYwAAFI: "MiBunny/027.png",
	AgADKwwAAhU6cEg: "NarkoLilAladin/000.png",
	AgAD0wgAAmxpeEg: "NarkoLilAladin/001.png",
	AgADFwkAAobXeEg: "NarkoLilAladin/002.png",
	AgADtAkAAoK1eUg: "NarkoLilAladin/003.png",
	AgADTQkAAnYreUg: "NarkoLilAladin/004.png",
	AgADQAoAA4h4SA: "NarkoLilAladin/005.png",
	"AgADgAoAAn-IeUg": "NarkoLilAladin/006.png",
	AgADPgoAAkRoeEg: "NarkoLilAladin/007.png",
	AgADGAwAAvE8eUg: "NarkoLilAladin/008.png",
	AgADcAkAAuE_eEg: "NarkoLilAladin/009.png",
	AgADGgcAAnT3eUg: "NarkoLilAladin/010.png",
	AgADowkAAmgQeUg: "NarkoLilAladin/011.png",
	AgAD2gcAAriHeEg: "NarkoLilAladin/012.png",
	AgAD1gkAAqn5eEg: "NarkoLilAladin/013.png",
	AgAD5wgAAjWteUg: "NarkoLilAladin/014.png",
	AgADNwgAArkCeEg: "NarkoLilAladin/015.png",
	AgADZQoAAh8veUg: "NarkoLilAladin/016.png",
	AgADlwoAAubLeEg: "NarkoLilAladin/017.png",
	AgADqQkAAkFKeUg: "NarkoLilAladin/018.png",
	AgADZgoAAgUzcUg: "NarkoLilAladin/019.png",
	AgADNggAAmb_cUg: "NarkoLilAladin/020.png",
	AgADdwkAAodNeEg: "NarkoLilAladin/021.png",
	AgADpgcAAqrieUg: "NarkoLilAladin/022.png",
	AgADiwgAAub8cUg: "NarkoLilAladin/023.png",
	AgADpQoAAn9_eUg: "NarkoLilAladin/024.png",
	AgADLQkAAun1eUg: "NarkoLilAladin/025.png",
	AgADWwgAApI_cEg: "NarkoLilAladin/026.png",
	AgADHAkAAjvxcUg: "NarkoLilAladin/027.png",
	AgADoQkAAkkNcUg: "NarkoLilAladin/028.png",
	AgADLQ4AAquAeEg: "NarkoLilAladin/029.png",
	AgADwgcAAnpyeEg: "NarkoLilAladin/030.png",
	"AgADTAkAAoF-eUg": "NarkoLilAladin/031.png",
	AgADmwgAAuEyeEg: "NarkoLilAladin/032.png",
	AgADKQkAArZCeEg: "NarkoLilAladin/033.png",
	AgADPAkAAt2zeEg: "NarkoLilAladin/034.png",
	AgADyggAAu5ucEg: "NarkoLilAladin/035.png",
	AgADUQsAAuyPeEg: "NarkoLilAladin/036.png",
	AgAD8AkAAjD9eUg: "NarkoLilAladin/037.png",
	AgADSAkAAm6KeEg: "NarkoLilAladin/038.png",
	AgADBAkAAhKSeEg: "NarkoLilAladin/039.png",
	AgAD1woAAkaxeUg: "NarkoLilAladin/040.png",
	AgADQQkAApzGeUg: "NarkoLilAladin/041.png",
	AgADzggAAsG1cEg: "NarkoLilAladin/042.png",
	AgADTQcAAvwNeUg: "NarkoLilAladin/043.png",
	AgADOgkAAlIeeEg: "NarkoLilAladin/044.png",
	AgADswkAAnBRcEg: "NarkoLilAladin/045.png",
	AgADFAoAAjPpeEg: "NarkoLilAladin/046.png",
	AgADYAkAArJKcUg: "NarkoLilAladin/047.png",
	AgADNggAAg0ZeEg: "NarkoLilAladin/048.png",
	AgADQQoAAuSZyUg: "NarkoLilAladin/049.png",
} as const;
