name: deploy
on:
  push:
    branches: [main]
permissions:
  contents: write
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v2
      
      - run: bun install --frozen-lockfile

      - run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - run: bun run deploy:preview
      - name: Deploy Release
        if: github.event_name == 'push' && contains(toLower(github.event.head_commit.message), 'release')
        run: bun run deploy